---
title: "實價登錄資料"
author: "ponponlin"
date: "2017年7月25日"
output:
  html_document: 
    highlight: haddock
    theme: spacelab
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE )
library(dplyr)
library(data.table)
library(raster)
library(rgdal)
library(geosphere)
library(ggplot2)
library(maptools)
library(gpclib)
library(ggmap)
### 村里界圖
shape<-readOGR(dsn="/Users/apple/nicole/R code/mission/村里界圖",layer="Village_NLSC_1050715") 
head(shape@data)
shape@data$CT_Name <- paste0(shape@data$T_Name,shape@data$Substitute)
tp=shape[shape@data$C_Name %in% c("臺北市"),]
### 台北村里清單
six <- read.csv("六都村里清單.csv", fileEncoding = "utf8", stringsAsFactors = F)
tp_village <- filter(six, 縣市名稱 == "台北市") 

```

<br/>

## 1. 資料來源
- [不動產成交案件實際資訊資料供應系統](http://plvr.land.moi.gov.tw/DownloadOpenData)
- 2015S1~2017S2 共十季的交易資料

## 2. 資料處理

### 台北市
> 目標一：得到每個裡的房價中位數

- 擷取104年以後之交易資料
- 去掉土地及車位的交易資料

> 目標二：得到每個里的屋齡中位數，每戶坪數中位數

- 保留全部時間的交易資料
- 去掉土地及車位的交易資料

```{r eval=FALSE}
A <- list()
for(i in 1:10){
  A[[i]] <- read.csv(paste("/Users/apple/nicole/OpenData/新實價登錄資料/S", "/A_lvr_land_A.CSV",sep = as.character(i)) ,fileEncoding = "big5")
}
price <- bind_rows(A)
price %>% 
  dplyr::select(-c(6,7,9,17:21,28)) %>% 
  filter(交易年月日 > 1040000,
              交易標的 %in% c("房地(土地+建物)", "房地(土地+建物)+車位", "建物"),
              單價每平方公尺 != 0) %>% 
  mutate(city = "台北市", 坪價 = as.numeric(單價每平方公尺)/0.3025) %>% 
  dplyr::select(city, 坪價, 1:19) -> tp_p

filter(tp_p, 建物移轉總面積平方公尺 ==0 )

tp_p %>% group_by(鄉鎮市區) %>% 
  summarise(n = n(), med = median(坪價), mean = mean(坪價)) # %>% View()

### 經緯轉換
# tp_loca <- data.frame(adress = tp_p$土地區段位置或建物區門牌, lon=as.numeric(121), lat = as.numeric(25))
# tp_loca$adress <- as.character(tp_loca$adress)
# 
# for(i in 1:1489){
#   a <- geocode(tp_loca$adress[i+1010])
#   tp_loca$lon[i+1010] <- a[1]
#   tp_loca$lat[i+1010] <- a[2]
#   print(i)
# }
# tp_loca$lon <- unlist(tp_loca$lon)
# tp_loca$lat <- unlist(tp_loca$lat)


### 匯出資料轉經緯度
# write.csv(tp_loca, "台北實價登錄地址.csv", fileEncoding = "big5", row.names = F)

```

### 不限104年
- 由於前面是要算房價錒，所以擷取出的資料是104年之後的，但又要在加算坪價跟屋齡，所以再把104年後的資料再去轉經緯度
- 用`ggmap`套件中的函式`geocode`轉經緯度，但一次只能轉2500筆

```{r eval=FALSE}
price %>% 
  dplyr::select(-c(6,7,9,17:21,28)) %>% 
  filter(交易年月日 < 1040000,
              交易標的 %in% c("房地(土地+建物)", "房地(土地+建物)+車位", "建物")) %>%
  mutate(city = "台北市", 坪價 = as.numeric(單價每平方公尺)/0.3025) %>% 
  dplyr::select(city, 坪價, 1:19) -> tp_pl
### 經緯轉換
tp_loca <- data.frame(adress = tp_pl$土地區段位置或建物區門牌, lon=as.numeric(121), lat = as.numeric(25))
tp_loca$adress <- as.character(tp_loca$adress)

# tp_loca <- read.csv("台北實價登錄地址2.csv", fileEncoding = "big5", stringsAsFactors = F)

# for(i in 1:671){
#   a <- geocode(tp_loca$adress[i+8508])
#   tp_loca$lon[i+8508] <- a[[1]]
#   tp_loca$lat[i+8508] <- a[[2]]
#   print(i)
# }

### 匯出資料轉經緯度
# write.csv(tp_loca, "台北實價登錄地址2.csv", fileEncoding = "big5", row.names = F)

```

### 經緯度找里
- 實價登錄資料地址不包含里，所以匯出轉經緯度
- 匯入村里界圖，利用轉好的經緯度去看落在哪個區里中

```{r eval=FALSE}
### 讀入轉好經緯度的地址
tp_loca <- read.csv("台北市實價登錄地址.csv", fileEncoding = "utf8") %>% dplyr::select(1:3)
tp_pl <- tp_pl %>% mutate(lon = tp_loca$lon, lat = tp_loca$lat)

### 實價登錄經緯度
ppts <- tp_pl[,c(22,23)]
ppts <- SpatialPoints(ppts)

### 村里界圖的里
li <- SpatialPolygons(tp@polygons)
### 確認 村里清單 與 村里界圖 相同
tp_v_Name <- as.character(tp$CT_Name)
dplyr::setdiff(tp_v_Name, tp_village$行政區域)
dplyr::setdiff(tp_village$行政區域, tp_v_Name)
tp_v_Name[tp_v_Name == "萬華區糖[部]里"] <- "萬華區糖廍里"
### 比對經緯度所在的里
tp_pl <- mutate(tp_pl, 里= tp_v_Name[over(ppts,li)])

dplyr::setdiff(tp_pl$里, tp_village$行政區域)
dplyr::setdiff(tp_village$行政區域, tp_pl$里)

# write.csv(tp_p, "台北市實價登錄全檔.csv", fileEncoding = "utf8", row.names = F)
# write.csv(tp_price, "台北市實價登錄.csv", fileEncoding = "utf8", row.names = F)

tp_pl<- mutate(tp_pl, 里= tp_v_Name[over(ppts,li)])

### 合併104前與104後
### 讀入之前已處理好的 台北市實價登錄全檔.csv
tp_p <- read.csv("台北市實價登錄全檔.csv", fileEncoding = "utf8", stringsAsFactors = F)
tp_price <- bind_rows(tp_p, tp_pl)

write.csv(tp_price, "台北市實價登錄全檔.csv", fileEncoding = "utf8", row.names = F)

```

### 整併資料
- 房價：取104年之後的資料做計算

```{r}
tp_price <- fread("台北市實價登錄全檔.csv")

### 算每個里的平均房價
tp_price %<>% filter(交易年月日 > 1040000) %>% 
  group_by(里) %>% 
  summarise(n = n(), med = median(坪價), mean = mean(坪價))
dplyr::setdiff(tp_price$里, tp_village$行政區域)
dplyr::setdiff(tp_village$行政區域, tp_price$里)

```



### 新北市

```{r}
A <- list()
for(i in 1:10){
  A[[i]] <- read.csv(paste("/Users/apple/nicole/OpenData/新實價登錄資料/S", "/F_lvr_land_A.CSV",sep = as.character(i)) ,fileEncoding = "big5")
}
np_price <- bind_rows(A)
np_price %>% 
  dplyr::select(-c(6,7,9,17:21,28)) %>% 
  filter(     交易標的 %in% c("房地(土地+建物)", "房地(土地+建物)+車位", "建物"),
              單價每平方公尺 != 0) %>% 
  mutate(city = "新北市", 坪價 = as.numeric(單價每平方公尺)/0.3025) %>% 
  dplyr::select(city, 坪價, 1:19) -> np_p

filter(np_p, 建物移轉總面積平方公尺 == 0 )

np_p %>% group_by(鄉鎮市區) %>% 
  summarise(n = n(), med = median(坪價), mean = mean(坪價))# %>% View()

```


### 一級發佈區 村里
- 經緯度編碼跟村里的不一樣
```{r }
plot(tp)
one<-readOGR(dsn="original_data/one",layer="G97_63000_U0201_2015") 
plot(one, add=T, border= "red")
head(one@data)
one <- spTransform(one, "+init=EPSG:4326")
plot(one)


```



