---
title: "綜合所得"
author: "ponponlin"
date: "2017年7月13日"
output: 
  html_document: 
    highlight: haddock
    theme: spacelab
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE )
library(dplyr)
```

<br/>

## 1. 資料來源
- [政府開放平台- 綜合所得稅所得總額各縣市鄉鎮村里統計分析表+縣市](http://data.gov.tw/wise_search?nodetype=metadataset&kw=%E7%B6%9C%E5%90%88%E6%89%80%E5%BE%97%E7%A8%85%E6%89%80%E5%BE%97%E7%B8%BD%E9%A1%8D%E5%90%84%E7%B8%A3%E5%B8%82%E9%84%89%E9%8E%AE%E6%9D%91%E9%87%8C%E7%B5%B1%E8%A8%88%E5%88%86%E6%9E%90%E8%A1%A8+%E7%B8%A3%E5%B8%82)可以下載到各個縣市的綜合所得稅所得表，有`101` 與 `102`年度
- 從[財政部業務統計網頁](http://www.fia.gov.tw/ct.asp?xItem=3759&ctNode=668&mp=1)有[103年度綜合所得稅申報核定統計專冊](http://www.fia.gov.tw/public/Attachment/77716484971.html)可以獲得 `103`年度的綜合所得稅所得表，但是資料為pdf檔與網頁，可以試試用爬蟲抓抓看
- 尚有[104年度綜合所得稅申報初步核定統計專冊](http://www.fia.gov.tw/public/Attachment/77716432171.html)可以獲得 `103`年度的綜合所得稅所得表，但是資料為pdf檔，不過為初步核定專冊

-------------

## 2. 資料處理
- 全台灣的所得稅所得為一個縣市一張表
- 編碼為 `UTF-8`
- 在讀入資料之前都必須先對原始 EXCEL 資料表前處理，且只能編輯一次，存檔後再打開就會變成亂碼了
- **與村里清單比較**
- [村里sheet.hub](https://sheethub.com/ronnywang/%E4%B8%AD%E8%8F%AF%E6%B0%91%E5%9C%8B%E6%9D%91%E9%87%8C/i/145/64)查詢，資料來源是政府開放平台的村里界圖資料
- 匯出成編碼 `UTF8`


### 高雄市
- `"左營區廍北里"`, `"左營區廍南里"` **廍** 字不見，在Excel裡貼上對的字，其他有顯示：`"阿蓮區峰山里"`，`"鳥松區坔埔里"`，`"湖內區公舘里"`

```{r}
### 讀入102年度綜合所得稅（高雄）
readLines(file("original_data/102年度綜合所得稅所得(高雄市).csv", encoding = "UTF8"), n = 1)
ks_income <- read.csv("original_data/102年度綜合所得稅所得(高雄市).csv", header = T,sep = "\t", stringsAsFactors = F)
ks_income %>% 
  filter(村里 != "其　他", 村里 != "合　計")  %>% 
  mutate(縣市 = "高雄市") %>% 
  select(11,1:10) -> ks_income

ks_village <- read.csv('高雄市村里清單.csv', fileEncoding = 'utf8', header = T, stringsAsFactors = F)
ks_income %>% mutate(行政區域 = paste0(鄉鎮市區 ,村里)) %>% 
  select(1,12,4:11) -> ks_income
### 所得資料有，村里清單沒有：
dplyr::setdiff(ks_income$行政區域, ks_village$行政區域)
### 村里清單有，所得資料沒有：
dplyr::setdiff(ks_village$行政區域, ks_income$行政區域)

### 里之間的合併
ks_income[ks_income$行政區域 == "左營區自立里",2] <- "左營區明建里"
ks_income[ks_income$行政區域 == "左營區復興里",2] <- "左營區永清里"
ks_income[ks_income$行政區域 == "左營區自治里",2] <- "左營區合群里"
ks_income[ks_income$行政區域 == "左營區自勉里",2] <- "左營區崇實里"
ks_income[ks_income$行政區域 == "三民區港北里",2] <- "三民區博愛里"
ks_income[ks_income$行政區域 == "鳳山區誠正里",2] <- "鳳山區生明里"
ks_income[ks_income$行政區域 == "鳳山區海風里",2] <- "鳳山區海光里"
ks_income[ks_income$行政區域 == "岡山區臺上里",2] <- "岡山區台上里"
ks_income[ks_income$行政區域 == "岡山區爲隨里",2] <- "岡山區為隨里"
ks_income[ks_income$行政區域 == "梓官區茄典里",2] <- "梓官區典寶里"
ks_income[ks_income$行政區域 == "阿蓮區峰山里",2] <- "阿蓮區峯山里"
ks_income[ks_income$行政區域 == "內門區內豐里",2] <- "內門區內豊里"
ks_income[ks_income$行政區域 == "那瑪夏區達卡努瓦",2] <- "那瑪夏區達卡努瓦里"

ks_income %>%  group_by(縣市,行政區域) %>% 
  summarise(納稅單位 =sum(納稅單位),綜合所得總額=sum(綜合所得總額),綜合所得平均數=mean(平均數),綜合所得中位數 = mean(中位數)) -> ks_income2
### 所得資料有，村里清單沒有：
dplyr::setdiff(ks_income2$行政區域, ks_village$行政區域)
### 村里清單有，所得資料沒有：
dplyr::setdiff(ks_village$行政區域, ks_income2$行政區域)
### 匯出
# write.csv(ks_income2,"2013高雄市綜合所得.csv", fileEncoding = "UTF8", row.names = F)

```

---------------

### 台中市

```{r}
tc_income <- read.csv("original_data/102年度綜合所得稅所得(台中市).csv", header = T,sep = "\t", stringsAsFactors = F)
tc_income %>% 
  filter(村里 != "其他", 村里 != "合計")  %>% 
  mutate(縣市 = "台中市") %>% 
  select(11,1:10) ->tc_income
tc_village <- read.csv('台中市村里清單.csv', fileEncoding = 'UTF8', header = T, stringsAsFactors = F)
tc_income %>% mutate(行政區域 = paste0(鄉鎮市區 ,村里)) %>% 
  select(1,12,4:11) -> tc_income

### 所得資料有，村里清單沒有：
dplyr::setdiff(tc_income$行政區域, tc_village$行政區域)
### 村里清單有，所得資料沒有：
dplyr::setdiff(tc_village$行政區域, tc_income$行政區域)

tc_income[tc_income$行政區域 == "東區富臺里",2] <- "東區富台里"
tc_income[tc_income$行政區域 == "北屯區󿾴子里",2] <- "北屯區廍子里"
tc_income[tc_income$行政區域 == "沙鹿區犂分里",2] <- "沙鹿區犁分里"
tc_income[tc_income$行政區域 ==  "外埔區󿾴子里" ,2] <-  "外埔區廍子里"
tc_income[tc_income$行政區域 == "大安區龜売里",2] <- "大安區龜壳里" 
tc_income[tc_income$行政區域 == "大肚區蔗󿾴里",2] <- "大肚區蔗廍里"
   tc_income[tc_income$行政區域 == "霧峰區丁臺里", 2] <- "霧峰區丁台里"

### 匯出
#    write.csv(tc_income,"2013台中市綜合所得.csv", fileEncoding = "UTF8", row.names = F)
```

---------------

### 新北市
- 石碇區碧山里併入永安里
- 樹林區西山里還不知道要改什麼里

```{r}
np_income <- read.csv("original_data/102年度綜合所得稅所得(新北市).csv", header = T,sep = "\t", stringsAsFactors = F)
np_income %>% 
  filter(村里 != "其　他", 村里 != "合　計")  %>% 
  mutate(縣市 = "新北市") %>% 
  select(11,1:10) -> np_income
six <- read.csv("六都村里清單.csv", fileEncoding = "utf8", stringsAsFactors = F)
np_village <- six %>% filter(縣市名稱 == "新北市")
np_income %>% mutate(行政區域 = paste0(鄉鎮市區 ,村里)) %>% 
  select(1,12,4:11) -> np_income
### 所得資料有，村里清單沒有：
a <- dplyr::setdiff(np_income$行政區域, np_village$行政區域); a
### 村里清單有，所得資料沒有：
dplyr::setdiff(np_village$行政區域, np_income$行政區域)
np_income[np_income$行政區域 == "新店區五峰里", "行政區域"] <- "新店區五峯里"
np_income[np_income$行政區域 == "板橋區公館里", "行政區域"] <- "板橋區公舘里"
np_income[np_income$行政區域 == "三峽區永館里", "行政區域"] <- "三峽區永舘里"
  np_income[np_income$行政區域 == a[5], "行政區域"] <- "樹林區獇寮里"
  np_income[np_income$行政區域 == a[7], "行政區域"] <- "中和區瓦磘里"
  np_income[np_income$行政區域 == a[8], "行政區域"] <- "中和區灰磘里"
  np_income[np_income$行政區域 == a[12], "行政區域"] <- "永和區新廍里"
  np_income[np_income$行政區域 == "土城區峰廷里", "行政區域"] <- "土城區峯廷里"
  np_income[np_income$行政區域 == "瑞芳區爪峰里", "行政區域"] <- "瑞芳區爪峯里"
  np_income[np_income$行政區域 == "萬里區崁腳里", "行政區域"] <- "萬里區崁脚里"
  np_income[np_income$行政區域 == "石碇區碧山里", "行政區域"] <- "石碇區永安里"
#  np_income[np_income$行政區域 == "樹林區西山里", "行政區域"] <-     
```

---------------

### 台南市

```{r}
tn_income <- read.csv("original_data/102年度綜合所得稅所得(台南市).csv", header = T,sep = "\t", stringsAsFactors = F)
tn_income %>% 
  filter(村里 != "其他", 村里 != "合計")  %>% 
  mutate(縣市 = "台南市") %>% 
  select(11,1:10) ->tn_income
tn_income %>% mutate(行政區域 = paste0(鄉鎮市區 ,村里)) %>% 
  select(1,12,4:11) -> tn_income
tn_village <- six %>% filter(縣市名稱 == "台南市")
### 所得資料有，村里清單沒有：
a <- dplyr::setdiff(tn_income$行政區域, tn_village$行政區域); a
### 村里清單有，所得資料沒有：
dplyr::setdiff(tn_village$行政區域, tn_income$行政區域)
tn_income[tn_income$行政區域 == a[1], "行政區域"] <- "安南區塭南里"
tn_income[tn_income$行政區域 == a[2], "行政區域"] <- "安南區公塭里"
tn_income[tn_income$行政區域 == a[3], "行政區域"] <- "安南區塩田里"
tn_income[tn_income$行政區域 == a[5], "行政區域"] <- "新營區舊廍里"
tn_income[tn_income$行政區域 == a[6], "行政區域"] <- "後壁區後廍里"
tn_income[tn_income$行政區域 == a[9], "行政區域"] <- "麻豆區寮廍里"
tn_income[tn_income$行政區域 == a[10], "行政區域"] <- "官田區南廍里"
tn_income[tn_income$行政區域 == a[12], "行政區域"] <- "佳里區頂廍里"
tn_income[tn_income$行政區域 == a[13], "行政區域"] <- "七股區塩埕里"
tn_income[tn_income$行政區域 == a[16], "行政區域"] <- "永康區塩行里"
tn_income[tn_income$行政區域 == a[17], "行政區域"] <- "永康區塩洲里"
tn_income[tn_income$行政區域 == "中西區赤崁里", "行政區域"] <- "中西區赤嵌里"
tn_income[tn_income$行政區域 == "後壁區菁豐里", "行政區域"] <- "後壁區菁豊里"
tn_income[tn_income$行政區域 ==  "麻豆區榖興里", "行政區域"] <- "麻豆區穀興里" 
tn_income[tn_income$行政區域 ==  "山上區玉峰里", "行政區域"]<- "山上區玉峯里"
tn_income[tn_income$行政區域 ==  "佳里區溪洲里", "行政區域"]<- "佳里區溪州里"
tn_income[tn_income$行政區域 ==  "新化區山腳里", "行政區域"]<- "新化區山脚里"

```

---------------

### 桃園市
- 有些村沒有改成里的要改成里
- 桃園區永和里不知道要改成什麼里

```{r}
ty_income <- read.csv("original_data/102年度綜合所得稅所得(桃園縣).csv", header = T,sep = "\t", stringsAsFactors = F)
ty_income %>% 
  filter(村里 != "其　他", 村里 != "合　計")  %>% 
  mutate(縣市 = "桃園市") %>% 
  select(11,1:10) ->ty_income
ty_income %>% mutate(行政區域 = paste0(鄉鎮市區 ,村里)) %>% 
  select(1,12,4:11) -> ty_income
ty_income$行政區域 <-  gsub("村","里",ty_income$行政區域)
ty_village <- six %>% filter(縣市名稱 == "桃園市")
### 所得資料有，村里清單沒有：
a <- dplyr::setdiff(ty_income$行政區域, ty_village$行政區域); a
### 村里清單有，所得資料沒有：
dplyr::setdiff(ty_village$行政區域, ty_income$行政區域)
#ty_income[ty_income$行政區域 ==  "桃園區永和里", "行政區域"] <- 
```

---------------

### 台北市
- 大同區文昌里併入老師里

```{r}
tp_income <- read.csv("original_data/102年度綜合所得稅所得(台北市).csv", header = T,sep = "\t", stringsAsFactors = F)
tp_income %>% 
  filter(村里 != "其　他", 村里 != "合　計")  %>% 
  mutate(縣市 = "台北市", 行政區域 = paste0(鄉鎮市區 ,村里)) %>% 
  dplyr::select(11,12,3:10) ->tp_income

tp_village <- six %>% filter(縣市名稱 == "台北市")
### 所得資料有，村里清單沒有：
a <- dplyr::setdiff(tp_income$行政區域, tp_village$行政區域); a
### 村里清單有，所得資料沒有：
dplyr::setdiff(tp_village$行政區域, tp_income$行政區域)
tp_income[tp_income$行政區域 == a[3], "行政區域"] <- "萬華區糖廍里"
tp_income[tp_income$行政區域 == a[1], "行政區域"] <- "大安區群賢里"
tp_income[tp_income$行政區域 == a[2], "行政區域"] <- "大安區群英里"
tp_income[tp_income$行政區域 == a[5], "行政區域"] <- "南港區舊莊里"
tp_income[tp_income$行政區域 == a[6], "行政區域"] <- "信義區富台里"
tp_income[tp_income$行政區域 == a[4], "行政區域"] <- "大同區老師里"

group_by(tp_income, 縣市,行政區域) %>%  
           summarise(納稅單位=mean(納稅單位), 綜合所得總額=mean(綜合所得總額), 平均數=mean(平均數), 中位數=mean(中位數), 第一分位數=mean(第一分位數), 第三分位數=mean(第三分位數), 標準差=mean(標準差), 變異係數=mean(變異係數)) -> tp_income
### 匯出
# write.csv(tp_income,"2013台北市綜合所得.csv", fileEncoding = "UTF8", row.names = F)
```

